### ISSUE TITLE
Unable to run super-AND repository in JupyterLab

### ISSUE THREAD

**Issue by selvipt** [super-AND/super-AND#2]
I am getting below error, while running this command python3 main.py --dataset cifar10 --network resnet18. For installation setup i just followed the steps mentioned in the github link.

`Downloading https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz to ./data/cifar-10-python.tar.gz

100.0%Extracting ./data/cifar-10-python.tar.gz to ./data

Files already downloaded and verified

Traceback (most recent call last):

  File "main.py", line 237, in <module>

    main()

  File "main.py", line 215, in main

    train(r, epoch, net, trainloader, optimizer, npc, criterion, criterion2, ANs_discovery, args.device)

  File "main.py", line 124, in train

    features = net(inputs) # (256, 128)

  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__

    result = self.forward(*input, **kwargs)

  File "/home/jovyan/super-AND/models/resnet_cifar.py", line 111, in forward

    out = self.layer2(out)

  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__

    result = self.forward(*input, **kwargs)

  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/torch/nn/modules/container.py", line 100, in forward

    input = module(input)

  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__

    result = self.forward(*input, **kwargs)

  File "/home/jovyan/super-AND/models/resnet_cifar.py", line 26, in forward

    out = F.relu(self.bn1(self.conv1(x)))

  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/torch/nn/functional.py", line 914, in relu

    result = torch.relu(input)

  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler

    _error_if_any_worker_fails()`

**Comment by Sungwon-Han** [comment]
Can you please share error messages (that are staying together with tracebacks)?

**Comment by super-AND** [comment]
Can you share the error message that is staying together with tracebacks?

**Comment by selvipt** [comment]
> Can you share the error message that is staying together with tracebacks?

(notebook) jovyan@jupyter-jupyterlab-2djupyterlab-2ddemo-2dqby9a1dq:~/super-AND$ python3 main.py --dataset cifar10 --network resnet18


Downloading https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz to ./data/cifar-10-python.tar.gz
100.0%Extracting ./data/cifar-10-python.tar.gz to ./data
Files already downloaded and verified
Traceback (most recent call last):
  File "main.py", line 237, in <module>
    main()
  File "main.py", line 215, in main
    train(r, epoch, net, trainloader, optimizer, npc, criterion, criterion2, ANs_discovery, args.device)
  File "main.py", line 124, in train
    features = net(inputs) # (256, 128)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jovyan/super-AND/models/resnet_cifar.py", line 111, in forward
    out = self.layer2(out)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jovyan/super-AND/models/resnet_cifar.py", line 27, in forward
    out = self.bn2(self.conv2(out))
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 345, in forward
    return self.conv2d_forward(input, self.weight)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 342, in conv2d_forward
    self.padding, self.dilation, self.groups)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 6514) is killed by signal: Killed.

**Comment by super-AND** [comment]
This problem may be related to the size of the memory (either CPU or GPU) your environment has.
Try running the code with the setting "workers = 0" or try using a smaller batch size to train your model.

Reference: https://github.com/pytorch/pytorch/issues/8976
